title = "PGiatasti"
baseURL = "/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "PGiatasti"
  description = "A lovely CTF team ❤️"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Github"
    url = "https://github.com/pgiatasti"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 2

[markup.goldmark.renderer]
  unsafe = false  # allow raw HTML in markdown files
